#ifndef ISAAC_CONSTANTS_HPP
#define ISAAC_CONSTANTS_HPP

#define GRAVITATIONAL_CONSTANT 6.6743E-11

#define TIME_STEP 1E-3

#define WORLD_WIDTH 100

#define WORLD_HEIGHT 100

#define WORLD_DEPTH 100

#define SCREEN_WIDTH 600

#define SCREEN_HEIGHT 600

#define SCREEN_DEPTH 0

#define BACKGROUND_COLOUR 0, 0, 0, 0

#endif // ISAAC_CONSTANTS_HPP
